Ventas.Web/Controllers/VendedoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using NPOI.HSSF.UserModel;
using System.IO;
using System.Web.Mvc;
using AutoMapper;
using Ventas.Servicios.Dtos;
using Ventas.Servicios.Impl;
using Ventas.Web.Models;


namespace Ventas.Web.Controllers
{
    [Authorize]
    public class VendedoresController : Controller
    {
        private ServicioVendedores _servicioVendedores;
        public VendedoresController()
        {
            _servicioVendedores = new ServicioVendedores();
        }

        public ActionResult Index()
        {
            return View(new VendedorSearchModel() { TipoBusqueda = "I" });
        }


        public PartialViewResult BuscarVendedores(string tipoBusqueda, string vendedorCodigo, string busqueda)
        {
            IEnumerable<VendedorDto> vendedores;
            if (string.IsNullOrEmpty(vendedorCodigo) && string.IsNullOrEmpty(busqueda))
            {
                vendedores = new List<VendedorDto>();
                @TempData["Success"] = "Ingrese un criterio de busqueda";
            }
            else
            {
                vendedores = _servicioVendedores.BuscarVendedores(busqueda);
                if (vendedores.Count() <= 0) @TempData["Success"] = "No se encontraron vendedores";
            }

            //var lista = Mapper.Map<IEnumerable<VendedorDto>, IList<VendedorListModel>>(vendedores);

            //foreach (var vendedor in lista.ToList())
            //{
            //    if (!String.IsNullOrEmpty(vendedor.Avatar))
            //    {
            //        //var usuarioDto = Mapper.Map<Vendedor, VendedorDto>(vendedor);
            //        var ruta = HttpContext.Current.Server.MapPath(@"~\AvatarVendedor");
            //        vendedor.AvatarIMG = new Imagen
            //        {
            //            Nombre = vendedor.Avatar,
            //            Contenido = File.ReadAllBytes(Path.Combine(ruta, vendedor.Avatar))
            //        };
            //    }
            //}

            if (tipoBusqueda == "B")
            {
                //Retorna la vista parcial para la busqueda de vendedores
                return PartialView("_VendedoresBusqueda", Mapper.Map<IEnumerable<VendedorDto>, IList<VendedorListModel>>(vendedores));
            }
            else
            {
                //Retorna la vista parcial para la busqueda de vendedores
                return PartialView("_VendedoresEncontrados", Mapper.Map<IEnumerable<VendedorDto>, IList<VendedorListModel>>(vendedores));
            }
        }

        public PartialViewResult Seleccionar()
        {
            //var modelo = new VendedorSearchModel()
            //{
            //    TipoBusqueda = "S"
            //};
            //return modelo;

            return PartialView("_Seleccionar",
                    new VendedorSearchModel() { TipoBusqueda = "B" }
                    );
        }
        public PartialViewResult Edit(int id)
        {
            VendedorDto vendedor = _servicioVendedores.Traer(id);

            return PartialView("_Edit", Mapper.Map<VendedorDto, VendedorEditModel>(vendedor));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(VendedorEditModel model, HttpPostedFileBase archivo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //public ActionResult Edit(VendedorEditModel model, HttpPostedFileBase archivo)
                    var vendedorDto = Mapper.Map<VendedorEditModel, VendedorDto>(model);

                    if (archivo != null && archivo.ContentLength > 0)
                    {
                        using (var lector = new BinaryReader(archivo.InputStream))
                        {
                            vendedorDto.Avatar = new Imagen()
                            {
                                Nombre = archivo.FileName,
                                Contenido = lector.ReadBytes(archivo.ContentLength)
                            };
                        }
                    }
                    _servicioVendedores.Update(vendedorDto);

                    //_servicioVendedores.Update(new VendedorDto()
                    //{
                    //    TipoVendedor = model.TipoVendedor,
                    //    Nombres = model.Nombres,
                    //    Apellidos = model.Apellidos,
                    //    TipoDocumento = model.TipoDocumento,
                    //    NumeroDocumento = model.NumeroDocumento,
                    //    CorreoElectronico = model.CorreoElectronico,
                    //    Telefono = model.Telefono,
                    //    Direccion = model.Direccion,
                    //    EquipoVenta = model.EquipoVenta,
                    //    FuerzaVenta = model.FuerzaVenta,
                    //    Supervisor = model.Supervisor,
                    //    Estado = model.Estado,
                    //    UltimoUsuario = model.UltimoUsuario,
                    //    UltimaFechaModif = model.UltimaFechaModif
                    //});
                }
                //ViewBag.Success = "Se Geolocalizo correctamente la dirección";
                TempData["Success"] = "Vendedor actualizado correctamente";
                return RedirectToAction("Browse", "Vendedor", new { id = model.VendedorId });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Aviso", "Hubo un Error: " + ex);
                //return RedirectToAction("Edit", "Vendedor", new { id = model.VendedorId });

                return RedirectToAction("_Edit", model);

                //throw;
            }

        }

        //public PartialViewResult Browse(int id)
        //{
        //    var vendedor = _servicioVendedores.Traer(id);

        //    return PartialView("_Browse", Mapper.Map<VendedorDto, VendedorViewModel>(vendedor));
        //}

        public ActionResult Browse(int id)
        {
            VendedorDto vendedor = _servicioVendedores.Traer(id);
            return View(
                Mapper.Map<VendedorDto, VendedorViewModel>(vendedor)
                );

            //var vendedor = _servicioVendedores.Traer(id);

            //return PartialView("_Browse", Mapper.Map<VendedorDto, VendedorViewModel>(vendedor));
        }

        public ActionResult Reporte(string id)
        {
            id = "a";
            IEnumerable<VendedorDto> vendedores;
            if (string.IsNullOrEmpty(id))
                vendedores = new List<VendedorDto>();
            else
                vendedores = _servicioVendedores.BuscarVendedores(id);

            var archivoExcel = new ReporteSimple().Exportar(id, vendedores.ToList());

            return File(archivoExcel, "application/vnd.ms-excel", "reporte_" + id + ".xls");
        }

        public class ReporteSimple
        {
            public byte[] Exportar(string BusquedaAnterior, List<VendedorDto> vendedores)
            {
                //logger.InfoFormat("Se exporto la busqueda de: {0}", BusquedaAnterior);

                // codigo del Reporte
                int numReg = vendedores.Count();
                //usar esto cuanto tienes un template
                //var nombreArchivo = NombreArchivo(); //@"d:\plantillas\balance.xlt";
                //var fs = new FileStream(nombreArchivo, FileMode.CreateNew);
                //var libro = new HSSFWorkbook(fs, true);




                var libro = new HSSFWorkbook();

                var hoja = libro.CreateSheet("Ejemplo Reporte");

                var fila = hoja.CreateRow(0);
                var celda = fila.CreateCell(0);
                celda.SetCellValue("Lista de Vendedores");
                //celda.CellStyle.WrapText = true;

                fila = hoja.CreateRow(1);
                celda = fila.CreateCell(0);
                celda.SetCellValue("Código");
                //celda.CellStyle.WrapText = true;

                celda = fila.CreateCell(1);
                celda.SetCellValue("Tipo Vendedor");
                //celda.CellStyle.WrapText = true;

                celda = fila.CreateCell(2);
                celda.SetCellValue("Nombes");
                //celda.CellStyle.WrapText = true;

                celda = fila.CreateCell(3);
                celda.SetCellValue("Documento");
                //celda.CellStyle.WrapText = true;

                celda = fila.CreateCell(4);
                celda.SetCellValue("Estado");
                //celda.CellStyle.WrapText = true;

                int count = 1;
                foreach (var vendedor in vendedores.ToList())
                {
                    count += 1;
                    fila = hoja.CreateRow(count);

                    celda = fila.CreateCell(0);
                    celda.SetCellValue(vendedor.VendedorId);
                    //celda.CellStyle.WrapText = true;

                    celda = fila.CreateCell(1);
                    celda.SetCellValue(vendedor.TipoVendedor);
                    //celda.CellStyle.WrapText = true;

                    celda = fila.CreateCell(2);
                    celda.SetCellValue(vendedor.Nombres);
                    //celda.CellStyle.WrapText = true;

                    celda = fila.CreateCell(3);
                    celda.SetCellValue(vendedor.NumeroDocumento);
                    //celda.CellStyle.WrapText = true;

                    celda = fila.CreateCell(4);
                    celda.SetCellValue(vendedor.Estado);
                    //celda.CellStyle.WrapText = true;
                }

                //var celda2 = fila1.CreateCell(1);
                //celda2.SetCellValue("10/01/2016");

                var mstream = new MemoryStream();

Ventas.Web/Views/Vendedores/Browse.cshtml
@model Ventas.Web.Models.VendedorViewModel

<div>
    <h4>VendedorViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VendedorId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendedorId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VendedorCodigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendedorCodigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoVendedor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoVendedor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CorreoElectronico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EquipoVenta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EquipoVenta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FuerzaVenta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FuerzaVenta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supervisor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supervisor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UltimoUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UltimoUsuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UltimaFechaModif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UltimaFechaModif)
        </dd>
        <dd>
            @if (Model.Avatar != null)
            {
                <div>
                    @Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(Model.Avatar.Contenido) + "\" class=\"img-thumbnail\" style=\"width: 100px; height: 100px; margin-bottom: 20px;\" />")
                </div>
            }
            else
            {
                <span>No tiene Avatar</span>
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Ventas.Web/Views/Vendedores/_Edit.cshtml
@model Ventas.Web.Models.VendedorEditModel
<div id="InscripcionFormContainer" class="container padding-top-10">

    @using (Html.BeginForm("Edit", "Vendedores", FormMethod.Post,
       new
       {
           enctype = "multipart/form-data",
           id = "IncripcionForm",
           @class = "form-horizontal form-group-smform-group-sm",
           role = "form"
       }
    ))
    {
        @Html.AntiForgeryToken()
        @*<div class="modal-dialog modal-lg">*@
        <div class="modal-dialog">
            @*<div class="modal-content">*@
            <div class="panel panel-default">
                <div class="panel-heading">
                    <button type="button"
                            class="close"
                            data-dismiss="modal"
                            aria-hidden="true">
                        &times;
                    </button>
                    <strong>
                        Modificar Vendedor @Model.VendedorCodigo
                    </strong>
                </div>
                <div class="panel-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.VendedorId)
                    <form>
                        <div class="row">
                            <div class="col-md-3 padding-top-10">
                                <label for="stateorregion" class="control-label">Tipo:</label>
                                @Html.EditorFor(model => model.TipoDocumento, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TipoDocumento, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-3 padding-top-10">
                                <label for="zipcode" class="control-label">Número:</label>
                                @Html.EditorFor(model => model.NumeroDocumento, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NumeroDocumento, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-6 padding-top-10">
                                <label for="city" class="control-label">Tipo Vendedor:</label>
                                @Html.EditorFor(model => model.TipoVendedor, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TipoVendedor, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 padding-top-10">
                                <label for="firstName" class="control-label">Nombres :</label>
                                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-6 padding-top-10">
                                <label for="firstName" class="control-label">Apellidos :</label>
                                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row padding-top-10">
                            <div class="col-md-12">
                                <label for="address1" class="control-label padding-top-10">Dirección:</label>
                                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 padding-top-10">
                                <label for="address1" class="control-label padding-top-10">Correo:</label>
                                @Html.EditorFor(model => model.CorreoElectronico, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CorreoElectronico, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-6 padding-top-10">
                                <label for="communicationpreference" class="control-label">Telefono:</label>
                                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 padding-top-10">
                                <label for="address1" class="control-label padding-top-10">Equipo de Venta:</label>
                                @Html.EditorFor(model => model.EquipoVenta, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.EquipoVenta, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-6 padding-top-10">
                                <label for="communicationpreference" class="control-label">Fuerza de Venta:</label>
                                @Html.EditorFor(model => model.FuerzaVenta, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.FuerzaVenta, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 padding-top-10">
                                <label for="city" class="control-label">Supervisor:</label>
                                @Html.EditorFor(model => model.Supervisor, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Supervisor, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-3 padding-top-10">
                                <label for="city" class="control-label">Estado:</label>
                                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-3 padding-top-10">
                                @*<label for="city" class="control-label">Avatar:</label>
                                @Html.EditorFor(model => model.Avatar, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })*@
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3 padding-top-10">
                                <label for="stateorregion" class="control-label">Usuario:</label>
                                @Html.EditorFor(model => model.UltimoUsuario, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UltimoUsuario, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-3 padding-top-10">
                                <label for="zipcode" class="control-label">Fecha:</label>
                                @Html.EditorFor(model => model.UltimaFechaModif, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UltimaFechaModif, "", new { @class = "text-danger" })
                            </div>
                            @*<div class="col-md-6 padding-top-10">

                            </div>*@
                            <div class="col-md-6 padding-top-10">
                                @Html.Label("Imagen", new { @class = "control-label col-md-6" })
                                <input type="file" name="archivo" class="btn btn-info col-md-12" />

                                @*@Html.LabelFor(m => m.Avatar, new { @class = "col-md-2 col-md-6" })*@
                                @*<div class="col-md-10">*@
                                 @*@Html.TextBoxFor(m => m.Avatar, new { type = "file" , @class="btn btn-info col-md-12"})*@
                                   
                                @*</div>*@

                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    <button type="submit" value="Save" class="btn btn-success" id="savebutton">
                        Grabar <i class="glyphicon glyphicon-floppy-disk"></i>
                    </button>
                </div>
            </div>
            @*</div>*@
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ventas.Web/Views/Vendedores/_Seleccionar.cshtml
@model Ventas.Web.Models.VendedorSearchModel

<div id="InscripcionFormContainer" class="container padding-top-10">
    @using (Ajax.BeginForm("BuscarVendedores", "Vendedores",
    new AjaxOptions
    {
        HttpMethod = "Get",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "ListaVendedoresEncontrados"
    },
    new
    {
        id = "BuscaVendedoresForm",
        @class = "form-horizontal"
    }
    ))
    {
        @*@using (Html.BeginForm("Busqueda", "Vendedores", FormMethod.Get,
               new
               {
                   enctype = "multipart/form-data",
                   id = "IncripcionForm",
                   @class = "form-horizontal form-group-sm",
                   role = "form"
               }
            ))
            {*@
        <div class="modal-dialog">
            @Html.AntiForgeryToken()
            <div class="panel panel-info padding-top-1">
                <div class="panel-heading">
                    <button type="button"
                            class="close"
                            data-dismiss="modal"
                            aria-hidden="true">
                        &times;
                    </button>
                    <strong>
                        Buscar Vendedores
                    </strong>
                </div>
                <div class="panel-body padding-top-1">
                    <div class="row">
                        @Html.HiddenFor(model => model.TipoBusqueda)
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="col-md-3 padding-top-10">
                            @Html.EditorFor(model => model.VendedoCodigo, new { htmlAttributes = new { @class = "form-control", @placeholder = "Código..." } })
                        </div>
                        <div class="col-md-7 padding-top-10">
                            @Html.EditorFor(model => model.Busqueda, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nombre y Apellidos..." } })
                        </div>
                        <div class="col-md-1 padding-top-10">
                            <input type="submit" value="Buscar" class="btn btn-default" />
                        </div>
                    </div>
                    <div id="ListaVendedoresEncontrados" class="panel panel-default table-responsive col-md-12">
                        @if (Model.Vendedores.Count() > 0)
                        {
                            @Html.Partial("_VendedoresBusqueda", Model.Vendedores) ;
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ventas.Web/Views/Vendedores/_VendedoresEncontrados.cshtml
@model IEnumerable<Ventas.Web.Models.VendedorListModel>

<script src="~/Scripts/app/datatable.js"></script>

<table id="myTable" class="table table-hover table-responsive table-condensed table-bordered">
    <thead >
        <tr>
            <th class="highlight">Código</th>
            <th class="highlight">Nombres</th>
            <th>Apellidos</th>
            <th>Dirección</th>
            <th>Estado</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody >
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.VendedorCodigo</td>
                <td>@item.Nombres</td>
                <td>@item.Apellidos</td>
                <td>@item.Direccion</td>
                <td>@item.Estado</td>
                <td>
                    @Ajax.ActionLink("  ", "Edit", "Vendedores",
                    new { id = item.VendedorId, area = "" },
                    new AjaxOptions
                    {
                        HttpMethod = "Get",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "InscripcionModalForm"
                    },
                    new
                    {
                        data_toggle = "modal",
                        data_target = "#InscripcionModalForm",
                        @class = "glyphicon glyphicon-map-marker"
                    })
                </td>
            </tr>
        }
    </tbody>
    @*<tfoot>
            <tr style="align-content:center">
                <td align="center"></td>
                <td align="center"></td>
                <td align="center"></td>
                <td align="center"></td>
                <td align="center"></td>
                <td align="center"></td>
            </tr>
        </tfoot>*@
</table>

<div id="InscripcionModalForm"
     class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="IncripcionFormLabel"
     aria-hidden="true">
</div>

<link rel="stylesheet" type="text/css" href="~/Content/dataTables.bootstrap.min.css">
<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap.min.js"></script>
@*<script>
        $(document).ready(function () {
            //$('#myTable tbody').hide()
            var table = $('#myTable').DataTable({
                " retrieve": true,
                "dom": "t<'col-sm-3'l><'col-sm-3'f><'col-sm-6'p>",
                //"dom": "<'bottom'><'col-sm-3'l><'col-sm-3'f><'col-sm-6'p>",
                "PaginationType": "full_numbers",
                "lengthMenu": [[15, 25, 50, -1], [15, 25, 50, "All"]],
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                //initComplete: function () {
                //    this.api().columns().every(function () {
                //        var column = this;
                //        var select = $('<select class="form-control input-sm"><option value=""></option></select>')
                //            .appendTo($(column.footer()).empty())
                //            .on('change', function () {
                //                var val = $.fn.dataTable.util.escapeRegex(
                //                    $(this).val()
                //                );

                //                column
                //                    .search(val ? '^' + val + '$' : '', true, true)
                //                    .draw();
                //            });
                //        column.data().unique().sort().each(function (d, j) {
                //            if (d.search("#InscripcionModalForm") < 0) {
                //                select.append('<option value="' + d + '">' + d + '</option>')
                //            }
                //        });
                //    });
                //}
            });

            $('#myTable tbody').on('dblclick', 'tr', function () {
                var data = table.row(this).data();
                alert('You clicked on ' + data[0] + '\'s row');
            });
            $('#myTable tbody').show()
            $('#myTable').show()
            //$('i.toggle-vis').on('click', function (e) {
            //    e.preventDefault();

            //    // Get the column API object
            //    var column = table.column($(this).attr('data-column'));

            //    // Toggle the visibility
            //    column.visible(!column.visible());
            //});
            //var table = $('#myTable').DataTable();

            //$('#myTable tbody').on('click', 'tr', function () {
            //    var data = table.row(this).data();
            //    alert('You clicked on ' + data[0] + '\'s row');
            //});
        });
    </script>*@

@section Scripts    {
    @Scripts.Render("~/bundles/unobtrusiveajax")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/paginacion")
}